quarkus.application.name=notification-service
quarkus.http.host=0.0.0.0

quarkus.http.port=8083

quarkus.swagger-ui.always-include=true
quarkus.devservices.enabled=false

# Kafka ? aponta para o servidor remoto
kafka.bootstrap.servers=192.168.68.112:9092

# Consumer ? escuta o topic order.created
mp.messaging.incoming.order-created.connector=smallrye-kafka
mp.messaging.incoming.order-created.topic=order.created
mp.messaging.incoming.order-created.group.id=notification-service
mp.messaging.incoming.order-created.auto.offset.reset=earliest
mp.messaging.incoming.order-created.value.deserializer=com.mello.nathalia.notification.consumer.OrderCreatedEventDeserializer

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://192.168.68.112:4317
quarkus.otel.service.name=notification-service

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://192.168.68.112:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=oCwQdhIlK496ruelY0Nn2ACjZpYBKAag
quarkus.oidc.token.issuer=http://192.168.68.112:8280/realms/ecommerce