quarkus.application.name=notification-service
quarkus.http.host=0.0.0.0

quarkus.http.port=8083

quarkus.swagger-ui.always-include=true
quarkus.devservices.enabled=false

# Kafka ? aponta para o servidor remoto
kafka.bootstrap.servers=${KAFKA_HOST:192.168.68.112}:9092

# Consumer ? escuta o topic order.created
mp.messaging.incoming.order-created.connector=smallrye-kafka
mp.messaging.incoming.order-created.topic=order.created
mp.messaging.incoming.order-created.group.id=notification-service
mp.messaging.incoming.order-created.auto.offset.reset=earliest
mp.messaging.incoming.order-created.value.deserializer=com.mello.nathalia.notification.domain.OrderCreatedEventDeserializer

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://${KAFKA_HOST:192.168.68.112}:4317
quarkus.otel.service.name=notification-service

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://${KAFKA_HOST:192.168.68.112}:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.token.issuer=http://${KAFKA_HOST:192.168.68.112}:8280/realms/ecommerce

# Groq API
groq.api.url=https://api.groq.com
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.1-8b-instant

# Groq REST Client
quarkus.rest-client.groq-api.url=${groq.api.url}