quarkus.application.name=api-gateway
quarkus.http.host=0.0.0.0

quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.devservices.enabled=false

# Serviços downstream
quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.order-service.url=http://localhost:8082

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://192.168.68.107:4317
quarkus.otel.service.name=api-gateway

# Métricas
quarkus.micrometer.export.prometheus.enabled=true