quarkus.application.name=api-gateway
quarkus.http.host=0.0.0.0

quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.devservices.enabled=false

# Serviços downstream
quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.order-service.url=http://localhost:8082

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://192.168.68.112:4317
quarkus.otel.service.name=api-gateway

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://192.168.68.112:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=oCwQdhIlK496ruelY0Nn2ACjZpYBKAag
quarkus.oidc.token.issuer=http://192.168.68.112:8280/realms/ecommerce
# Propaga o token JWT automaticamente para os RestClients
quarkus.rest-client.propagate-headers=Authorization