quarkus.application.name=api-gateway
quarkus.http.host=0.0.0.0

quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.devservices.enabled=false

# Serviços downstream
quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.order-service.url=http://localhost:8082

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://${INFRA_HOST}:4317
quarkus.otel.service.name=api-gateway

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://${INFRA_HOST}:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.token.issuer=http://${INFRA_HOST}:8280/realms/ecommerce
# Propaga o token JWT automaticamente para os RestClients
quarkus.rest-client.propagate-headers=Authorization

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,Idempotency-Key
quarkus.http.cors.exposed-headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true