global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    scrape_interval: 15s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['192.168.68.110:8080']

  - job_name: 'user-service'
    scrape_interval: 15s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['192.168.68.110:8081']

  - job_name: 'order-service'
    scrape_interval: 15s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['192.168.68.110:8082']

  - job_name: 'notification-service'
    scrape_interval: 15s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['192.168.68.110:8083']