quarkus.application.name=user-service
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${INFRA_HOST}:5432/userdb
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8081

quarkus.swagger-ui.always-include=true

quarkus.devservices.enabled=false

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://${INFRA_HOST}:4317
quarkus.otel.service.name=user-service

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://${INFRA_HOST}:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.token.issuer=http://${INFRA_HOST}:8280/realms/ecommerce