quarkus.application.name=user-service
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.68.107:5432/userdb
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8081

quarkus.swagger-ui.always-include=true

quarkus.devservices.enabled=false

# Observabilidade
quarkus.otel.exporter.otlp.endpoint=http://192.168.68.107:4317
quarkus.otel.service.name=user-service

# Métricas
quarkus.micrometer.export.prometheus.enabled=true

quarkus.oidc.auth-server-url=http://192.168.68.107:8280/realms/ecommerce
quarkus.oidc.client-id=ecommerce-app
quarkus.oidc.credentials.secret=oCwQdhIlK496ruelY0Nn2ACjZpYBKAag
quarkus.oidc.token.issuer=http://192.168.68.107:8280/realms/ecommerce