quarkus.application.name=order-service

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.68.110:5433/orderdb

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8082

quarkus.swagger-ui.always-include=true

quarkus.devservices.enabled=false

# URL do user-service ? o order-service vai chamar esse endereço
quarkus.rest-client.user-service.url=http://localhost:8081

# Kafka ? servidor remoto
kafka.bootstrap.servers=192.168.68.110:9092

# Producer ? publica no topic order.created
mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order.created
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer